spring.application.name=
spring.threads.virtual.enabled=

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=
spring.jpa.show-sql=
spring.jpa.properties.hibernate.format_sql=

app.security.cors-allowed-origin=

app.security.jwt-secret=
app.security.jwt-ttl-minutes=

spring.mail.host=
spring.mail.port=
spring.mail.username=
spring.mail.password=

spring.mail.properties.mail.smtp.auth=
spring.mail.properties.mail.smtp.starttls.enable=
#app.mail.from=
app.mail.from=

app.frontend.reset-password-url=

logging.level.org.springframework.web=
