spring.application.name=loan
spring.threads.virtual.enabled=true

spring.datasource.url=jdbc:postgresql://localhost:5432/qudu2
spring.datasource.username=postgres
spring.datasource.password=051412

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

app.security.cors-allowed-origin=http://localhost:4200

app.security.jwt-secret=JvuAfV1jRMtMxnq7dFqc6a7fWA9GkNDh
app.security.jwt-ttl-minutes=10000000005

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=Ehe90987@gmail.com
spring.mail.password=zhas npub qlzg bway

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.frontend.reset-password-url=http://localhost:4200/reset-password/{token}

logging.level.org.springframework.web=DEBUG
