spring.application.name=loan

spring.datasource.url=jdbc:postgresql://localhost:5432/qudu2
spring.datasource.username=postgres
spring.datasource.password=051412

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false