if [ -z "${BASH_VERSION:-}" ]; then
    exec bash "$0" "$@"
fi

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

ENV_LOCAL=".env.local"
APP_CONTAINER="qudu-be"
WAIT_SECONDS="${WAIT_SECONDS:-300}"

export ENV_FILE="$ENV_LOCAL"

compose() {
    docker compose --env-file "$ENV_LOCAL" \
        -f docker-compose.yml -f docker-compose.local.yml "$@"
}

say()  { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m!!\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31mxx\033[0m %s\n' "$*" >&2; exit 1; }

random_hex() {
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -hex "$1"
    else
        head -c "$1" /dev/urandom | od -An -tx1 | tr -d ' \n'
    fi
}

require_docker() {
    command -v docker >/dev/null 2>&1 || die "docker is not installed or not on PATH."
    if ! docker info >/dev/null 2>&1; then
        die "The Docker engine is not running. Start Docker Desktop and wait for 'Engine running'. If it refuses to start, check that virtualization is enabled in the BIOS."
    fi
    docker compose version >/dev/null 2>&1 || die "'docker compose' (v2) is not available."
}

require_env_local() {
    [ -f "$ENV_LOCAL" ] || die "$ENV_LOCAL does not exist yet; run: bash scripts/docker-local.sh up"
}

ensure_env_local() {
    if [ -f "$ENV_LOCAL" ]; then
        return
    fi
    say "Creating $ENV_LOCAL with generated secrets"
    {
        echo "# Local Docker test settings. Generated by scripts/docker-local.sh."
        echo "# Gitignored. Not used on any server."
        echo
        echo "APP_PORT=8080"
        echo
        echo "# ---- database container ----"
        echo "# The app reaches it as \"db\" inside the compose network;"
        echo "# docker-compose.local.yml sets DB_URL for that. From this machine"
        echo "# (DBeaver, psql) use localhost:DB_HOST_PORT."
        echo "DB_NAME=qudu2"
        echo "DB_USERNAME=qudu"
        echo "DB_PASSWORD=$(random_hex 16)"
        echo "DB_HOST_PORT=5433"
        echo
        echo "# ---- security ----"
        echo "JWT_SECRET=$(random_hex 32)"
        echo "JWT_TTL_MINUTES=30"
        echo "REFRESH_TTL_DAYS=7"
        echo "CORS_ALLOWED_ORIGIN=http://localhost:4200"
        echo
        echo "# ---- mail ----"
        echo "# Left blank: the app starts, and sending mail fails when it is tried."
        echo "MAIL_HOST=smtp.gmail.com"
        echo "MAIL_PORT=587"
        echo "MAIL_USERNAME="
        echo "MAIL_PASSWORD="
        echo "MAIL_FROM="
        echo "FRONTEND_RESET_PASSWORD_URL=http://localhost:4200/reset-password/{token}"
        echo
        echo "API_DOCS_ENABLED=true"
        echo
        echo "# ---- push notifications ----"
        echo "FIREBASE_ENABLED=false"
        echo "FIREBASE_CREDENTIALS_PATH=file:/app/secrets/firebase-credentials.json"
    } > "$ENV_LOCAL"
    chmod 600 "$ENV_LOCAL" 2>/dev/null || true
}

env_value() {
    sed -n "s/^$1=//p" "$ENV_LOCAL" | tail -n 1 | tr -d '\r'
}

port_busy() {
    command -v netstat >/dev/null 2>&1 || return 1
    netstat -an 2>/dev/null | grep -Eq "[:.]$1[[:space:]].*LISTEN"
}

check_ports() {
    local app_port db_port
    app_port="$(env_value APP_PORT)"; app_port="${app_port:-8080}"
    db_port="$(env_value DB_HOST_PORT)"; db_port="${db_port:-5433}"

    # Ports held by our own running containers are fine.
    if docker ps --format '{{.Names}}' | grep -qx "$APP_CONTAINER"; then
        return
    fi
    if port_busy "$app_port"; then
        die "Port $app_port is already in use (a backend started from the IDE?). Stop it, or change APP_PORT in $ENV_LOCAL."
    fi
    if port_busy "$db_port"; then
        die "Port $db_port is already in use. Change DB_HOST_PORT in $ENV_LOCAL."
    fi
}

wait_healthy() {
    say "Waiting for $APP_CONTAINER to become healthy (up to ${WAIT_SECONDS}s)"
    local waited=0 state health
    while [ "$waited" -lt "$WAIT_SECONDS" ]; do
        state="$(docker inspect -f '{{.State.Status}}' "$APP_CONTAINER" 2>/dev/null || echo missing)"
        health="$(docker inspect -f '{{if .State.Health}}{{.State.Health.Status}}{{end}}' "$APP_CONTAINER" 2>/dev/null || true)"
        case "$state/$health" in
            running/healthy)
                printf '\n'
                return 0 ;;
            exited/*|dead/*|missing/*)
                printf '\n'
                warn "Container is $state. Last log lines:"
                docker logs --tail 60 "$APP_CONTAINER" 2>&1 || true
                return 1 ;;
        esac
        printf '.'
        sleep 5
        waited=$((waited + 5))
    done
    printf '\n'
    warn "Still not healthy after ${WAIT_SECONDS}s (state=$state, health=${health:-none}). Last log lines:"
    docker logs --tail 60 "$APP_CONTAINER" 2>&1 || true
    return 1
}

cmd_up() {
    require_docker
    ensure_env_local
    mkdir -p secrets
    check_ports

    say "Building the image and starting db + app"
    compose up -d --build

    wait_healthy || die "The backend did not come up. Full log: bash scripts/docker-local.sh logs"

    local app_port db_port
    app_port="$(env_value APP_PORT)"; app_port="${app_port:-8080}"
    db_port="$(env_value DB_HOST_PORT)"; db_port="${db_port:-5433}"

    say "Smoke test: GET /api/plafonds/catalog"
    curl -fsS "http://localhost:${app_port}/api/plafonds/catalog"
    printf '\n\n'

    say "Running"
    echo "  Backend     http://localhost:${app_port}"
    echo "  Swagger UI  http://localhost:${app_port}/swagger-ui.html"
    echo "  Database    localhost:${db_port}  db=$(env_value DB_NAME)  user=$(env_value DB_USERNAME)"
    echo "              password: DB_PASSWORD in $ENV_LOCAL"
    echo "  Uploads     docker volume qudu-be_uploads (/app/uploads in the container)"
    echo
    echo "  The database starts empty: there is no seed data, so nobody can sign in"
    echo "  until roles, menus and a SUPERADMIN user are inserted."
}

cmd_status() { require_docker; require_env_local; compose ps; }
cmd_logs()   { require_docker; require_env_local; compose logs -f --tail 200 app; }

cmd_psql() {
    require_docker
    require_env_local
    compose exec db psql -U "$(env_value DB_USERNAME)" -d "$(env_value DB_NAME)"
}

cmd_down() {
    require_docker
    require_env_local
    compose down
    say "Stopped. Database and uploads volumes are kept."
}

cmd_reset() {
    require_docker
    require_env_local
    if [ "${1:-}" != "--yes" ]; then
        printf 'This deletes the LOCAL test database and uploaded files (volumes qudu-be_pgdata, qudu-be_uploads). Type "yes": '
        read -r answer
        [ "$answer" = "yes" ] || die "Aborted."
    fi
    compose down -v
    say "Stopped and removed the local volumes."
}

case "${1:-up}" in
    up)     cmd_up ;;
    status) cmd_status ;;
    logs)   cmd_logs ;;
    psql)   cmd_psql ;;
    down)   cmd_down ;;
    reset)  shift; cmd_reset "${1:-}" ;;
    -h|--help|help)
        sed -n '2,15p' "$0" | sed 's/^# \{0,1\}//' ;;
    *)
        die "Unknown command '$1'. Use: up | status | logs | psql | down | reset" ;;
esac
